name: MagicSpells
main: com.nisovin.magicspells.MagicSpells
version: VERSION_STRING
author: nisovin
softdepend: [Vault,ProtocolLib,WorldGuard,Residence]
commands:
    magicspellcast:
        description: Cast a spell
        usage: /<command>
        aliases: [cast,c]
    magicspellmana:
        description: Show mana bar
        usage: /<command>
        aliases: [mana]
    magicspellxp:
        description: Show magic XP info
        usage: /<command>
        aliases: [magicxp,spellxp]
    hello:
        description: It replies with a greeting to the player!
        usage: /<command>
    class:
        description: This command will set the player class
        usage: /<command>